import "./globals.css"; // Import global CSS styles
import MyContext from "@/LearnContext/Context"; // 🎯 Import the MyContext component from Context.js

export const metadata = { // Metadata object containing title and description
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) { // Define a component named RootLayout which takes children as props
  return (
    <html lang="en"> {/* HTML tag with language set to English */}
      <body> {/* Body tag */}
        <MyContext> {/* 🎯🎯 Use MyContext as a wrapper */}
          {children} {/* Render children components within MyContext */}
        </MyContext>
      </body>
    </html>
  );
}
